apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsRoot: false
      containers:
      - name: redis
        image: redis:7.2.4
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc 