name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.2.4
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: YourStrongPassword
        options: >-
          --requirepass YourStrongPassword
          --health-cmd "redis-cli -a YourStrongPassword ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      vault:
        image: hashicorp/vault:1.15.2
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
          VAULT_DEV_TLS_DISABLE: 1
        options: >-
          --cap-add=IPC_LOCK
          --health-cmd "vault status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      REDIS_PASSWORD: YourStrongPassword

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Wait for Vault to be ready
      run: |
        timeout 30s bash -c 'until curl -s http://127.0.0.1:8200/v1/sys/health > /dev/null; do sleep 1; done'

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=.

    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --cov=.

    - name: Run performance tests
      run: |
        pytest tests/performance/ -v --cov=.

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true